{% set name = "google-cloud-ndb" %}
{% set version = "2.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_ndb-{{ version }}.tar.gz
  sha256: 13eb3d8a81afcdb0627ec535be27a99312c0966a7b1d170afb169840a84ab439

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - grpcio
    - requests
    - python >={{ python_min }}
    - google-api-core >=2.11.0,<3.0.0
    - google-cloud-datastore !=2.20.2,<3.0.0,>=2.16.0
    - protobuf >=4.25.8,<8.0.0
    - pymemcache <5.0.0,>=2.1.0
    - pytz >=2018.3
    - redis-py <7.0.0,>=3.0.0

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/python-ndb
  summary: NDB library for Google Cloud Datastore
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
