{% set name = "google-cloud-ndb" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/google_cloud_ndb-{{ version }}.tar.gz
  sha256: 44e64e25a15f168ddff0f8c5a7288f7b0256ec51737948388df58b0ddc22586f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - grpcio
    - requests
    - python >={{ python_min }}
    - google-api-core <3.0.0,>=2.11.0
    - google-cloud-datastore >=2.16.0,!=2.20.2,<3.0.0
    - protobuf <8.0.0,>=4.25.8
    - pymemcache >=2.1.0,<5.0.0
    - pytz >=2018.3
    - redis-py >=3.0.0,<8.0.0

test:
  imports:
    - google
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/python-ndb
  summary: NDB library for Google Cloud Datastore
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
